# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/chatbot?useSSL=false
    username: manager
    password: mk123456
    driver-class-name: com.mysql.jdbc.Driver

#这是mybatis所使用的配置
mybatis:
  # 告诉mybatis对应的实体类位置
  type-aliases-package: cn.insectmk.chatbotweb.entity
  # 告诉mybatisSQL的映射文件在这里
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  global-config:
    db-config:
      # 表名前缀
      table-prefix: t_
      # id生成策略 数据库自增
      id-type: auto
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


