# 应用服务 WEB 访问端口
server:
  port: 8080

# Spring相关配置
spring:
  # 配置文件选择
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

# 这是MyBatis所使用的配置
mybatis:
  # 告诉mybatis对应的实体类位置
  type-aliases-package: cn.insectmk.chatbotweb.entity
  # 告诉mybatisSQL的映射文件在这里
  mapper-locations: classpath*:mapper/*.xml

# 这是MyBatisPlus的配置
mybatis-plus:
  global-config:
    db-config:
      # 表名前缀
      table-prefix: t_
      # id生成策略 数据库自增
      id-type: auto
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
